/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

#include <stdio.h>
#define MAXFIBNUM 4000000

int main()
{
    int first = 1;
    int second = 1;
    int fib = 0;
    int sum = 0;

    printf("project euler 2nd problem");

    do
    {
        if(second % 2 == 0)
            sum = sum + second;
        fib = first + second;
        first = second;
        second = fib;
    }while(second < MAXFIBNUM);

    printf("\n%d", sum);

    return 0;
}
